keys:
  - &host_TheOracle age14ju8288fj59hh3xw5zqx8tklpyhp23gzc8fhj9m5l46h0vwxtuuqugmxzz
  - &host_QBX age14jmmdjz3gpnk9zq9ph3vwjat45hqdcqysxxpnwvnnp929sq5he7qcs3fc8

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *host_TheOracle
          - *host_QBX
